In [55]:
# It seems there was an issue with the previous approach. Let's debug and fix it.

import random
import pandas as pd

file_path_csv = './experiment_conditions.csv'
df_loaded_csv = pd.read_csv(file_path_csv)
display(df_loaded_csv)

SEARCHED = False
while not SEARCHED:
    random_number = random.randint(0, 26)
    random_col = random.choice(df_loaded_csv.columns)
    if pd.isna(df_loaded_csv.iloc[random_number][random_col]):
        df_loaded_csv.loc[random_number, random_col] = 'Marked'
        print('Marked',random_col, random_number)
        SEARCHED = True
    else:
        print('Already marked',random_col, random_number)
df_loaded_csv.to_csv(file_path_csv, index=False)

   baseline proposed
0       NaN      NaN
1       NaN      NaN
2       NaN      NaN
3       NaN      NaN
4       NaN      NaN
5       NaN      NaN
6       NaN      NaN
7       NaN      NaN
8       NaN      NaN
9       NaN      NaN
10      NaN      NaN
11      NaN      NaN
12      NaN      NaN
13      NaN      NaN
14      NaN      NaN
15      NaN      NaN
16      NaN      NaN
17      NaN      NaN
18      NaN      NaN
19      NaN      NaN
20      NaN      NaN
21      NaN      NaN
22      NaN      NaN
23      NaN      NaN
24      NaN      NaN
25      NaN      NaN
26      NaN      NaN
27      End      End

Marked proposed 26